version: '3'

services:
  app:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    container_name: micro-service-loopback-app
    ports:
      - 3001:3000
    environment:
      - HOST=0.0.0.0
    volumes:
      - .:/home/node/app
    networks:
      - app-network
      - rabbitmq_micro-service


networks:
  app-network:
    driver: bridge
  rabbitmq_micro-service:
    external: true
